name: check
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Indented correctly under 'build'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Build Nix derivation
        run: |
          nix build .#bible-verify

